# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
