# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_trip_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='uid',
            field=models.CharField(default='trip_DGSaVP4YlgGRVmON1M7KTRASJYt', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
