# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20170511_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tag_line',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
