# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_auto_20170508_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='uid',
            field=models.CharField(editable=False, max_length=42, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='uid',
            field=models.CharField(editable=False, max_length=42, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
