# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20170509_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='uid',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='uid',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
