# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_auto_20170701_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='title',
            new_name='address',
        ),
    ]
