# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_auto_20170701_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destination.Destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('MAIN', 'main'), ('ARRI', 'arrival'), ('DEPT', 'departure'), ('POI', 'point of interest')], default='MAIN', max_length=4),
        ),
    ]
