# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0004_auto_20170705_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='address',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longitude',
        ),
        migrations.AddField(
            model_name='destination',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
