# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-19 14:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_auto_20170719_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='data',
        ),
        migrations.AddField(
            model_name='destination',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_place_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='destination',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True, verbose_name='Longitude'),
        ),
    ]
