# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_trip_tag_line'),
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set([('trip', 'email')]),
        ),
    ]
