# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20170619_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
