# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0003_invite_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='is_active',
        ),
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('C', 'cancelled'), ('a', 'accepted'), ('r', 'rejected')], default='p', max_length=1),
        ),
    ]
