# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170506_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default='fruhgfurhrhu', editable=False, max_length=42, unique=True),
            preserve_default=False,
        ),
    ]
