# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
