# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170622_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identifier',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
