# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170622_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identifier',
            new_name='auth0_id',
        ),
    ]
